PREFIX ?= $(CONDA_ENV_PATH)
INSTALL_PREFIX = $(PREFIX)
INCLUDEPATH = $(PREFIX)/include
LIBPATH = $(PREFIX)/lib
LDFLAGS = -Wl,-rpath $(LIBPATH)
OPT_LIBS = -lhdf5 -lhdf5_hl -lnetcdf
LIBS = $(OPT_LIBS) -lnetcdff -llapack95 -llapack -lblas

COMPILE = gfortran -c -O2 -fbacktrace -Warray-bounds -fopenmp -ffree-line-length-0
LINK = gfortran -Warray-bounds -Wall -fopenmp -O2 -o

include makefile.common
